title_name = "nx1"
title_id = "4156089E" #
hash = "A49321A07235881F" # 2-nx1mp.xex
#media_id = "00000000"

[[patch]]
    name = "stub MAssertVargs"
    author = "and799"
    is_enabled = true

    [[patch.be32]]
        address = 0x82527570
        value = 0x4E800020

[[patch]]
    name = "120 FPS"
    desc = "Unlocks vsync, requires vsync = false in Xenia config."
    author = "Taleb, Clippy95"
    is_enabled = true

    [[patch.be32]]
        address = 0x82453010 # com_maxfps
        value = 0x38800078
    [[patch.be32]]
        address = 0x82812054 # r_vsync
        value = 0x38800000

[[patch]]
    name = "Aspect ratio"
    author = "Clippy95"
    is_enabled = false

    [[patch.f32]]
        address = 0x8214053C
        value = 2.38888888889
		
[[patch]]
    name = "720p"
    desc = "Makes the game run at 720p instead of 600p. Currently disables AA until a solution's found."
    author = "Tervel"
    is_enabled = false

    [[patch.be16]]
        address = 0x82807626
        value = 0x0500
    [[patch.be16]]
        address = 0x8280762A
        value = 0x02D0
		
[[patch]]
    name = "Skip Blackbox Connect"
    author = "Tervel"
    is_enabled = true

    [[patch.be32]]
        address = 0x82529CA0
        value = 0x4E800020
		
[[patch]]
    name = "Remove white flickering box"
    desc = "disables gp_rdvar_camo_enabled which caused flickering on the top left of the screen"
    author = "Clippy95, and799"
    is_enabled = true

    [[patch.be32]]
        address = 0x82810EF0
        value = 0x38A02000

[[patch]]
    name = "Ingame Console Fix"
    desc = "Ingame Console Fix for Xenia keyboard passthrough"
    author = "And799"
    is_enabled = true

    [[patch.be32]]
        address = 0x8259F284 
        value = 0x6000000


[[patch]]
    name = "Disable Debug OSD"
    author = "xinerki"
    is_enabled = true

    [[patch.be8]]
        address = 0x822412F3 # cg_drawFPS
        value = 0

    [[patch.be8]]
        address = 0x82241317 # cg_drawViewpos
        value = 0

    [[patch.be8]]
        address = 0x8245313B # com_statmon
        value = 0
