title_name = "Black Ops 2"
title_id = "415608C3" #
hash = "0CB2A0C60096D201" # default_mp.xex
#media_id = "00000000"

[[patch]]
    name = "idk"
    author = "xinerki"
    is_enabled = false

    [[patch.be8]]
        address = 0x82433827
        value = 1

    [[patch.be8]]
        address = 0x83EBEFED
        value = 1

[[patch]]
    name = "nop piracy check"
    author = "xinerki"
    is_enabled = true

    [[patch.be32]]
        address = 0x82220F10
        value = 0x60000000

[[patch]]
    name = "nop LiveStorage process"
    author = "xinerki"
    is_enabled = true

    [[patch.be32]]
        address = 0x8251E300
        value = 0x60000000

[[patch]]
    name = "unlocked fps"
    author = "xinerki"
    is_enabled = true

    [[patch.be8]]
        address = 0x82738AD7 # r_vsync
        value = 0
    
    [[patch.be8]]
        address = 0x8236F7E3 # com_maxfps
        value = 240