title_name = "Call Of Duty 3" # MP TU0
title_id = "415607E1" #AV-2017
hash = "D1CC65DC0F0C0CBB" # codmp_xenonf.xex
#media_id = "2E07093A" # Disc (USA, Europe): http://redump.org/disc/12479/

[[patch]]
    name = "Remove Grass"
    desc = "Fixes stretching grass artifact."
    author = "Clippy95"
    is_enabled = false

    [[patch.be32]]
        address = 0x82410f78
        value = 0x4e800020

[[patch]]
    name = "Disable Depth Of Field"
    desc = "Fixes blurring entire screen when ADS"
    author = "Clippy95"
    is_enabled = false

    [[patch.be32]]
        address = 0x825744EC
        value = 0x60000000
    [[patch.be32]]
        address = 0x825744F4
        value = 0x60000000
    [[patch.f32]]
        address = 0x82c77e44
        value = 100000

[[patch]]
    name = "Aspect Ratio"
    author = "Clippy95"
    is_enabled = false

    [[patch.f32]]
        address = 0x82085b6c
        value = 2.38888888889

[[patch]]
    name = "cg_fov"
    author = "Clippy95"
    is_enabled = false

    [[patch.string]]
        address = 0x82078610
        value = "90"
