title_name = "Black Ops 2"
title_id = "415608C3" #
hash = "B2E78AE54365E2B2" # default_.xex
#media_id = "00000000"

[[patch]]
    name = "nop piracy check"
    author = "xinerki"
    is_enabled = true

    [[patch.be32]]
        address = 0x821EB17C
        value = 0x60000000

[[patch]]
    name = "unlocked fps (doesnt work)"
    author = "xinerki"
    is_enabled = false

    [[patch.be8]]
        address = 0x82658F47 # r_vsync
        value = 0
    
    [[patch.be8]]
        address = 0x8235837C # com_maxfps
        value = 240