title_name = "nx1"
title_id = "4156089E" # 
hash = "3C876080C1FFB9AB" # 1-nx1sp.xex
#media_id = "00000000"

[[patch]]
    name = "stub MAssertVargs"
    author = "and799"
    is_enabled = true

    [[patch.be32]]
        address = 0x824bcd10
        value = 0x4E800020

[[patch]]
    name = "Ingame Console Fix"
    desc = "Ingame Console Fix for Xenia keyboard passthrough"
    author = "And799"
    is_enabled = true

    [[patch.be32]]
        address = 0x8251E97C
        value = 0x6000000