title_name = "Call Of Duty 3" # MP TU3
title_id = "415607E1" #AV-2017
hash = "C4EA5EACCA7CA7CD" # codmp_xenonf.xex
#media_id = "2E07093A" # Disc (USA, Europe): http://redump.org/disc/12479/

[[patch]]
    name = "Remove Grass"
    desc = "Fixes stretching grass artifact."
    author = "Clippy95"
    is_enabled = false

    [[patch.be32]]
        address = 0x823d6450
        value = 0x4e800020

[[patch]]
    name = "Disable Depth Of Field"
    desc = "Fixes blurring entire screen when ADS"
    author = "Clippy95"
    is_enabled = false

    [[patch.be32]]
        address = 0x82539be4 # ADS
        value = 0x60000000
    [[patch.be32]]
        address = 0x82429888 # Death screen
        value = 0x60000000
    [[patch.be32]]
        address = 0x820c1888
        value = 0x60000000
    [[patch.f32]]
        address = 0x82c37d24
        value = 100000

[[patch]]
    name = "Aspect Ratio"
    author = "Clippy95"
    is_enabled = false

    [[patch.f32]]
        address = 0x8207bf4c
        value = 2.38888888889
