title_name = "Modern Warfare 3" # Call Of Duty Ghosts May 08 2013
title_id = "4156088E"
hash = "6705EC8F1206F62D" # 2-iw6mp.exe
#media_id = "00000000"

[[patch]]
    name = "Force 720p"
    desc = "Makes the game run at 1280x720 instead of the default 1024x600"
    author = "Clippy95"
    is_enabled = true

    [[patch.be8]]
        address = 0x8297B707
        value = 0x01

[[patch]]
    name = "Disable Whitelist"
    author = "Taleb"
    is_enabled = true

    [[patch.be32]]
        address = 0x8287FF0C
        value = 0x60000000

[[patch]]
    name = "240 FPS"
    author = "Clippy95"
    is_enabled = true

    [[patch.be16]]
        address = 0x82691186 # com_maxfps
        value = 0x00F0
    [[patch.be8]]
        address = 0x8297C947 # r_vsync
        value = 0x00
