title_name = "nx1"
title_id = "4156089E" # 
hash = "CBFAA079004C987F" # 5-nx1mp_demo.xex
#media_id = "00000000"

[[patch]]
    name = "140 FPS"
    desc = "Unlocks vsync, requires vsync = false in Xenia config."
    author = "Taleb, Clippy95"
    is_enabled = true

    [[patch.be32]]
        address = 0x822D9B88 # com_maxfps
        value = 0x38800078
    [[patch.be32]]
        address = 0x824D563C # r_vsync
        value = 0x38800000

[[patch]]
    name = "Aspect ratio"
    author = "Clippy95"
    is_enabled = false

    [[patch.f32]]
        address = 0x82088764
        value = 2.38888888889
		
[[patch]]
    name = "Skip Blackbox Connect"
    author = "Tervel, Adrian"
    is_enabled = true

    [[patch.be32]]
        address = 0x823591B8
        value = 0x4E800020
		
[[patch]]
    name = "Remove white flickering box"
    desc = "disables gp_rdvar_camo_enabled which caused flickering on the top left of the screen"
    author = "Clippy95, and799"
    is_enabled = true

    [[patch.be16]]
        address = 0x824D4736
        value = 0x2000

